package traefikazadjwtvalidator

import (
	"encoding/json"
)

// AzureJwt represents the Json Web Tokens generated by Azure.
type AzureJwt struct {
	Header     AzureJwtHeader
	Payload    Claims
	Signature  []byte
	RawToken   []byte
	RawPayload []byte
}

// AzureJwtHeader represents the Json Web Token Headers generated by Azure.
type AzureJwtHeader struct {
	Alg string `json:"alg"`
	Kid string `json:"kid"`
	Typ string `json:"typ"`
}

// Claims represents the default attributes included in a Json Web Token generated by Azure.
type Claims struct {
	Iat   json.Number `json:"iat"`
	Exp   json.Number `json:"exp"`
	Iss   string      `json:"iss"`
	Aud   []string    `json:"aud"`
	Sub   string      `json:"sub"`
	Roles []string    `json:"roles"`
}
